// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFilesByPickingDirectory(arg1) {
  return window['go']['main']['App']['GetFilesByPickingDirectory'](arg1);
}

export function GetFilesByPickingFiles() {
  return window['go']['main']['App']['GetFilesByPickingFiles']();
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}
