name: Wails build

on:
  push:
    tags:
      - 'v*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: '--max-old-space-size=4096'

jobs:
  build:
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: true
      matrix:
        build:
          - name: 'FileRenamer'
            platform: 'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'FileRenamer'
            platform: 'windows/amd64'
            os: 'windows-latest'
            nsis: true
          - name: 'FileRenamer.exe'
            platform: 'windows/amd64'
            os: 'windows-latest'
            nsis: false
          - name: 'FileRenamer'
            platform: 'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          nsis: ${{ matrix.build.nsis }}
          go-version: 1.22
          node-version: latest
